// Step 1: Meet the Pieces. Order follows the beginner sequence in Chess for
// Children, Part 1 (board → long-range pieces → queen and king → pawns and
// knights → setup → mini-games). All wording here is original.

import { board, START_FEN, EMPTY_FEN } from "../authoring";
import type { Lesson } from "../types";

const SRC = "Chess for Children, Part 1 (topic order)";

export const step1: Lesson[] = [
  {
    id: "s1-board",
    step: 1,
    title: "The Chessboard",
    kidTitle: "The Board Is a Town",
    goal: "Kids can put the board the right way round and name rows, columns and diagonals.",
    minutes: 15,
    materials: ["One board per pair", "Optional: masking tape to mark one corner"],
    script: [
      {
        say: "This is a chessboard. It has 64 squares, light and dark, taking turns like a checkerboard.",
        do: "Show the empty board on screen and hold up a real board.",
        demo: { fen: EMPTY_FEN },
      },
      {
        say: "Before we play, we always check one thing: the corner square on your right-hand side must be light. Say it with me: light on the right!",
        do: "Have every pair turn their board so the bottom-right square is light.",
        demo: { fen: EMPTY_FEN, highlight: ["h1", "a8"] },
      },
      {
        say: "Lines of squares going side to side are called rows. Lines going up and down, from you to your partner, are called columns.",
        demo: { fen: EMPTY_FEN, highlight: ["a3", "b3", "c3", "d3", "e3", "f3", "g3", "h3"] },
      },
      {
        say: "Squares that touch corner to corner make a slanted line called a diagonal. A diagonal is always one color.",
        demo: { fen: EMPTY_FEN, highlight: ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8"] },
      },
      {
        say: "Every square has a name: a letter for its column and a number for its row. This square is e4.",
        do: "Grade 3 and up only. Skip this beat for K–2.",
        demo: { fen: EMPTY_FEN, highlight: ["e4"] },
      },
    ],
    k2Tip: "Call rows 'streets' and columns 'roads'. Skip square names; just play 'touch the square I point to'.",
    commonMistakes: ["Board turned the wrong way (dark square on the right). Check every board before each game."],
    activity: {
      title: "Row, Column, Diagonal",
      kidTitle: "Simon Says Squares",
      minutes: 5,
      setup: "Pairs with an empty board.",
      rules: [
        "The teacher calls out 'row', 'column' or 'diagonal'.",
        "Kids trace one with a finger as fast as they can.",
        "Older kids: the teacher calls a square name (like c6) and partners race to touch it.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "tap",
        fen: EMPTY_FEN,
        prompt: { text: "Tap the corner square on White's right-hand side.", kid: "Tap the corner on the right, near you." },
        answers: ["h1"],
        hint: { text: "White sits at the bottom of the screen. Look at the bottom-right corner." },
      },
      {
        id: "p2",
        kind: "choice",
        prompt: { text: "Is the corner square on your right light or dark?", kid: "The corner on your right is…" },
        options: [{ text: "Light" }, { text: "Dark" }],
        answer: 0,
        hint: { text: "Light on the right!" },
      },
      {
        id: "p3",
        kind: "tap",
        fen: EMPTY_FEN,
        prompt: { text: "Tap the square e4.", kid: "Tap the square with the star on it." },
        answers: ["e4"],
        kidMarks: ["e4"],
        hint: { text: "Find column e along the bottom, then go up to row 4." },
      },
      {
        id: "p4",
        kind: "choice",
        prompt: { text: "How many squares are on a chessboard?" },
        options: [{ text: "32" }, { text: "64" }, { text: "100" }],
        answer: 1,
      },
    ],
    check: [
      {
        id: "c1",
        kind: "choice",
        prompt: { text: "Which corner square must be light when you set up the board?", kid: "Which corner is light?" },
        options: [{ text: "The one on your right" }, { text: "The one on your left" }],
        answer: 0,
      },
      {
        id: "c2",
        kind: "choice",
        prompt: { text: "A slanted line of squares that touch at the corners is called a…" },
        options: [{ text: "Row" }, { text: "Column" }, { text: "Diagonal" }],
        answer: 2,
      },
      {
        id: "c3",
        kind: "tap",
        fen: EMPTY_FEN,
        prompt: { text: "Tap the corner square in the top-left.", kid: "Tap the corner at the top, on the left." },
        answers: ["a8"],
      },
    ],
    passMark: 2,
    sources: [SRC],
  },

  {
    id: "s1-rook",
    step: 1,
    title: "The Rook",
    kidTitle: "The Rook Goes Straight",
    goal: "Kids can move a rook, see when it is blocked, and capture with it.",
    minutes: 15,
    materials: ["One board per pair", "Rooks and pawns"],
    script: [
      {
        say: "Meet the rook. It looks like a castle tower. The rook moves in straight lines: up, down, left or right, as far as it wants.",
        do: "Hold up a rook.",
        demo: { fen: board({ R: "d4" }), arrows: [{ from: "d4", to: "d8" }, { from: "d4", to: "d1" }, { from: "d4", to: "a4" }, { from: "d4", to: "h4" }] },
      },
      {
        say: "The rook can't jump. If one of its own pieces is in the way, it has to stop before it.",
        demo: { fen: board({ R: "d4", P: "d6" }), arrows: [{ from: "d4", to: "d5" }] },
      },
      {
        say: "If an enemy piece is in the way, the rook can capture it. It lands on that square and the enemy piece leaves the board.",
        demo: { fen: board({ R: "d4", p: "g4" }), arrows: [{ from: "d4", to: "g4" }] },
      },
      {
        say: "Each player starts with two rooks, one in each corner.",
        demo: { fen: START_FEN, highlight: ["a1", "h1", "a8", "h8"] },
      },
    ],
    k2Tip: "Rooks drive like cars on roads: straight only, no turning in the middle of a move.",
    commonMistakes: ["Moving the rook around a corner in one move.", "Jumping over a piece."],
    activity: {
      title: "Rook vs. Pawns",
      kidTitle: "Rook Rescue",
      minutes: 10,
      setup: "White: one rook on a1. Black: pawns on a7, b7, c7 and d7.",
      rules: [
        "White moves first. Take turns, one move each.",
        "The rook wins by capturing every pawn.",
        "The pawns win if one reaches the other side of the board.",
        "Swap sides and play again.",
      ],
      fen: board({ R: "a1", p: ["a7", "b7", "c7", "d7"] }),
      game: { win: "captureAll", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "reach",
        fen: board({ R: "d4" }),
        square: "d4",
        prompt: { text: "Tap every square the rook can move to.", kid: "Tap all the places the rook can go." },
      },
      {
        id: "p2",
        kind: "stars",
        fen: board({ R: "a1" }),
        square: "a1",
        stars: ["h8"],
        prompt: { text: "Get the rook to the star in as few moves as you can.", kid: "Drive the rook to the star!" },
        hint: { text: "A rook can't go on a slant. Try going up, then across." },
      },
      {
        id: "p3",
        kind: "reach",
        fen: board({ R: "c3", P: ["c6", "f3"] }),
        square: "c3",
        prompt: { text: "Your pawns are in the way. Tap every square the rook can move to.", kid: "Tap where the rook can go. It can't jump!" },
      },
      {
        id: "p4",
        kind: "move",
        fen: board({ R: "b2", p: ["b6", "e5"] }),
        goal: "capture",
        answers: ["b2b6"],
        prompt: { text: "Capture a pawn with the rook.", kid: "Take a pawn with the rook!" },
        hint: { text: "Only one pawn is on a straight line from the rook." },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "reach",
        fen: board({ R: "f5", P: "f7", p: "c5" }),
        square: "f5",
        prompt: { text: "Tap every square the rook can move to.", kid: "Tap all the places the rook can go." },
      },
      {
        id: "c2",
        kind: "stars",
        fen: board({ R: "h1" }),
        square: "h1",
        stars: ["a8"],
        prompt: { text: "Get the rook to the star in as few moves as you can.", kid: "Drive the rook to the star!" },
      },
      {
        id: "c3",
        kind: "move",
        fen: board({ R: "e1", p: ["c3", "e6", "h4"] }),
        goal: "capture",
        answers: ["e1e6"],
        prompt: { text: "Capture a pawn with the rook.", kid: "Take a pawn with the rook!" },
      },
    ],
    passMark: 2,
    sources: [SRC],
  },

  {
    id: "s1-bishop",
    step: 1,
    title: "The Bishop",
    kidTitle: "The Bishop Goes Slanty",
    goal: "Kids can move a bishop along diagonals and know it always stays on one color.",
    minutes: 15,
    materials: ["One board per pair", "Bishops and pawns"],
    script: [
      {
        say: "This is the bishop. It has a pointy hat. The bishop moves on diagonals, the slanted lines, as far as it wants.",
        do: "Hold up a bishop.",
        demo: { fen: board({ B: "d4" }), arrows: [{ from: "d4", to: "a7" }, { from: "d4", to: "h8" }, { from: "d4", to: "a1" }, { from: "d4", to: "g1" }] },
      },
      {
        say: "Look at the color of the bishop's square. It never changes! A bishop that starts on a light square stays on light squares all game.",
        demo: { fen: board({ B: "c1", b: "f8" }), highlight: ["c1", "f8"] },
      },
      {
        say: "Like the rook, the bishop can't jump. It captures by landing on an enemy piece.",
        demo: { fen: board({ B: "c1", p: "g5", P: "b2" }), arrows: [{ from: "c1", to: "g5" }] },
      },
      {
        say: "Each player has two bishops: one for the light squares and one for the dark squares.",
        demo: { fen: START_FEN, highlight: ["c1", "f1", "c8", "f8"] },
      },
    ],
    k2Tip: "Bishops ski down slopes. They always stay on their own color, like a skier who only uses one trail.",
    commonMistakes: ["Sliding one square straight up (that's a rook move)."],
    activity: {
      title: "Bishop vs. Pawns",
      kidTitle: "Bishop Chase",
      minutes: 10,
      setup: "White: bishops on c1 and f1. Black: pawns on a7, b7, c7, d7, e7 and f7.",
      rules: [
        "White moves first. Take turns.",
        "The bishops win by capturing every pawn.",
        "The pawns win if one reaches the other side.",
        "Swap sides and play again.",
      ],
      fen: board({ B: ["c1", "f1"], p: ["a7", "b7", "c7", "d7", "e7", "f7"] }),
      game: { win: "captureAll", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "reach",
        fen: board({ B: "d4" }),
        square: "d4",
        prompt: { text: "Tap every square the bishop can move to.", kid: "Tap all the places the bishop can go." },
      },
      {
        id: "p2",
        kind: "stars",
        fen: board({ B: "c1" }),
        square: "c1",
        stars: ["h6"],
        prompt: { text: "Get the bishop to the star.", kid: "Slide the bishop to the star!" },
      },
      {
        id: "p3",
        kind: "choice",
        fen: board({ B: "f1" }),
        prompt: { text: "This bishop is on a light square. Can it ever reach a dark square?" },
        options: [{ text: "Yes" }, { text: "No" }],
        answer: 1,
        hint: { text: "Diagonals are always one color." },
      },
      {
        id: "p4",
        kind: "move",
        fen: board({ B: "e3", p: ["e6", "b6", "h3"] }),
        goal: "capture",
        answers: ["e3b6"],
        prompt: { text: "Capture a pawn with the bishop.", kid: "Take a pawn with the bishop!" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "reach",
        fen: board({ B: "c4", P: "e6" }),
        square: "c4",
        prompt: { text: "Tap every square the bishop can move to.", kid: "Tap all the places the bishop can go." },
      },
      {
        id: "c2",
        kind: "stars",
        fen: board({ B: "a1" }),
        square: "a1",
        stars: ["a7"],
        prompt: { text: "Get the bishop to the star in as few moves as you can.", kid: "Slide the bishop to the star!" },
      },
      {
        id: "c3",
        kind: "move",
        fen: board({ B: "d2", p: ["d6", "a5", "h2"] }),
        goal: "capture",
        answers: ["d2a5"],
        prompt: { text: "Capture a pawn with the bishop.", kid: "Take a pawn with the bishop!" },
      },
    ],
    passMark: 2,
    sources: [SRC],
  },

  {
    id: "s1-queen-king",
    step: 1,
    title: "The Queen and the King",
    kidTitle: "The Queen and the King",
    goal: "Kids can move the queen (rook + bishop) and the king (one square any way).",
    minutes: 15,
    materials: ["One board per pair", "Queens, kings and pawns"],
    script: [
      {
        say: "The queen is the strongest piece. She moves like a rook and a bishop put together: straight or slanted, as far as she wants.",
        do: "Hold up a queen.",
        demo: {
          fen: board({ Q: "d4" }),
          arrows: [
            { from: "d4", to: "d8" }, { from: "d4", to: "h4" }, { from: "d4", to: "d1" }, { from: "d4", to: "a4" },
            { from: "d4", to: "h8" }, { from: "d4", to: "a7" }, { from: "d4", to: "a1" }, { from: "d4", to: "g1" },
          ],
        },
      },
      {
        say: "The king is the most important piece. If your king gets trapped, you lose! But he moves slowly: just one square in any direction.",
        do: "Hold up a king.",
        demo: { fen: board({ K: "e4" }), highlight: ["d3", "e3", "f3", "d4", "f4", "d5", "e5", "f5"] },
      },
      {
        say: "At the start, the queen goes on her own color: the white queen on a light square, the black queen on a dark square. The king goes next to her.",
        demo: { fen: START_FEN, highlight: ["d1", "e1", "d8", "e8"] },
      },
    ],
    k2Tip: "The queen is a superhero who can fly any direction. The king is a grandpa who takes one small step at a time.",
    commonMistakes: ["Moving the queen like a knight.", "Moving the king two squares (outside of castling, taught later)."],
    activity: {
      title: "Queen vs. Pawns",
      kidTitle: "Queen Sweep",
      minutes: 10,
      setup: "White: a queen on d1. Black: all eight pawns on their starting squares.",
      rules: [
        "White moves first. Take turns.",
        "The queen wins by capturing every pawn.",
        "The pawns win if one reaches the other side, or if they capture the queen.",
        "Swap sides and play again.",
      ],
      fen: board({ Q: "d1", p: ["a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7"] }),
      game: { win: "captureAll", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "reach",
        fen: board({ Q: "d4" }),
        square: "d4",
        prompt: { text: "Tap every square the queen can move to.", kid: "Tap all the places the queen can go." },
      },
      {
        id: "p2",
        kind: "reach",
        fen: board({ K: "e4" }),
        square: "e4",
        prompt: { text: "Tap every square the king can move to.", kid: "Tap all the places the king can go." },
      },
      {
        id: "p3",
        kind: "stars",
        fen: board({ K: "a1" }),
        square: "a1",
        stars: ["d4"],
        prompt: { text: "Walk the king to the star in as few moves as you can.", kid: "Walk the king to the star!" },
        hint: { text: "Walking on a slant gets there fastest." },
      },
      {
        id: "p4",
        kind: "move",
        fen: board({ Q: "c2", p: ["c7", "g6"], P: "c5" }),
        goal: "capture",
        answers: ["c2g6"],
        prompt: { text: "Capture a pawn with the queen.", kid: "Take a pawn with the queen!" },
        hint: { text: "Your own pawn blocks one path." },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "reach",
        fen: board({ Q: "b2", P: "b5" }),
        square: "b2",
        prompt: { text: "Tap every square the queen can move to.", kid: "Tap all the places the queen can go." },
      },
      {
        id: "c2",
        kind: "reach",
        fen: board({ K: "h1" }),
        square: "h1",
        prompt: { text: "Tap every square the king can move to.", kid: "Tap all the places the king can go." },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Which piece is the strongest?" },
        options: [{ text: "King" }, { text: "Queen" }, { text: "Rook" }],
        answer: 1,
      },
      {
        id: "c4",
        kind: "move",
        fen: board({ Q: "a1", p: ["a8", "h8"], P: "a4" }),
        goal: "capture",
        answers: ["a1h8"],
        prompt: { text: "Capture a pawn with the queen.", kid: "Take a pawn with the queen!" },
      },
    ],
    passMark: 3,
    sources: [SRC],
  },

  {
    id: "s1-knight",
    step: 1,
    title: "The Knight",
    kidTitle: "The Jumping Horse",
    goal: "Kids can move a knight in an L and know it jumps over pieces.",
    minutes: 15,
    materials: ["One board per pair", "Knights and pawns"],
    script: [
      {
        say: "The knight looks like a horse, and it moves in a funny way: two squares straight, then one square to the side. It makes a capital L.",
        do: "Hold up a knight.",
        demo: { fen: board({ N: "d4" }), highlight: ["c6", "e6", "f5", "f3", "e2", "c2", "b3", "b5"] },
      },
      {
        say: "Here's a trick: a knight always lands on the other color. If it starts on a light square, it lands on a dark one.",
        demo: { fen: board({ N: "g1" }), highlight: ["f3", "h3", "e2"] },
      },
      {
        say: "The knight is the only piece that can jump over other pieces, friends or enemies. It only captures the piece where it lands.",
        demo: { fen: board({ N: "b1", P: ["a2", "b2", "c2"], p: "c3" }), arrows: [{ from: "b1", to: "c3" }] },
      },
    ],
    k2Tip: "Count it out loud with the kids: 'One, two, turn!' Knights are the trickiest piece for young kids, so expect to repeat this lesson.",
    commonMistakes: ["Moving one square diagonally and calling it an L.", "Stopping after two squares."],
    activity: {
      title: "Knight vs. Pawns",
      kidTitle: "Horse and Pawns",
      minutes: 10,
      setup: "White: a knight on b1. Black: pawns on b7, c7 and d7.",
      rules: [
        "White moves first. Take turns.",
        "The knight wins by capturing every pawn.",
        "The pawns win if one reaches the other side.",
        "This is harder than it looks! Swap sides and play again.",
      ],
      fen: board({ N: "b1", p: ["b7", "c7", "d7"] }),
      game: { win: "captureAll", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "reach",
        fen: board({ N: "d4" }),
        square: "d4",
        prompt: { text: "Tap every square the knight can jump to.", kid: "Tap all the places the horse can jump." },
      },
      {
        id: "p2",
        kind: "reach",
        fen: board({ N: "a1" }),
        square: "a1",
        prompt: { text: "A knight in the corner. Tap every square it can jump to.", kid: "Tap where the horse in the corner can go." },
        hint: { text: "Knights in corners don't have many choices." },
      },
      {
        id: "p3",
        kind: "stars",
        fen: board({ N: "b1" }),
        square: "b1",
        stars: ["b3"],
        prompt: { text: "Jump the knight to the star in as few moves as you can.", kid: "Hop the horse to the star!" },
        hint: { text: "It can't get there in one jump. Try two." },
      },
      {
        id: "p4",
        kind: "move",
        fen: board({ N: "e4", P: ["d5", "e5", "f5", "d3", "e3", "f3"], p: ["c3", "e7"] }),
        goal: "capture",
        answers: ["e4c3"],
        prompt: { text: "The knight is surrounded! Capture a pawn anyway.", kid: "Jump over and take a pawn!" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "reach",
        fen: board({ N: "f3" }),
        square: "f3",
        prompt: { text: "Tap every square the knight can jump to.", kid: "Tap all the places the horse can jump." },
      },
      {
        id: "c2",
        kind: "stars",
        fen: board({ N: "g1" }),
        square: "g1",
        stars: ["g5"],
        prompt: { text: "Jump the knight to the star in as few moves as you can.", kid: "Hop the horse to the star!" },
      },
      {
        id: "c3",
        kind: "move",
        fen: board({ N: "c3", p: ["c5", "d5", "e3"] }),
        goal: "capture",
        answers: ["c3d5"],
        prompt: { text: "Capture a pawn with the knight.", kid: "Take a pawn with the horse!" },
      },
    ],
    passMark: 2,
    sources: [SRC],
  },

  {
    id: "s1-pawn",
    step: 1,
    title: "The Pawn",
    kidTitle: "Little Pawns, Big Dreams",
    goal: "Kids can move pawns forward, use the two-square first move, and capture diagonally.",
    minutes: 20,
    materials: ["One board per pair", "Eight pawns per side"],
    script: [
      {
        say: "Pawns are the little pieces in front. Each player has eight. A pawn moves straight forward one square. It can never go backward.",
        demo: { fen: board({ P: "e3" }), arrows: [{ from: "e3", to: "e4" }] },
      },
      {
        say: "On its very first move, a pawn may take one or two steps forward. After that, only one.",
        demo: { fen: board({ P: "d2" }), highlight: ["d3", "d4"] },
      },
      {
        say: "Here's the tricky part: pawns capture differently than they move. A pawn captures one square diagonally forward. It can't capture the piece straight in front of it.",
        demo: { fen: board({ P: "e4", p: ["e5", "d5"] }), arrows: [{ from: "e4", to: "d5" }] },
      },
      {
        say: "If a pawn marches all the way to the other side, it turns into a queen, or any other piece you want! We'll practice that in a later lesson.",
        demo: { fen: board({ P: "a7" }), arrows: [{ from: "a7", to: "a8" }] },
      },
    ],
    k2Tip: "Pawns walk straight but grab on the slant. Have kids 'walk' two fingers forward and 'grab' diagonally.",
    commonMistakes: ["Capturing straight ahead.", "Moving two squares after the first move.", "Moving backward."],
    activity: {
      title: "Pawn Wars",
      kidTitle: "Pawn Wars",
      minutes: 15,
      setup: "Only pawns: all eight white pawns and all eight black pawns on their starting squares.",
      rules: [
        "White moves first. Take turns, one pawn move each.",
        "The first player to get a pawn to the other side wins.",
        "If it's your turn and you can't move, the game is a draw.",
        "Play again, switching colors.",
      ],
      fen: board({ P: ["a2", "b2", "c2", "d2", "e2", "f2", "g2", "h2"], p: ["a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7"] }),
      game: { win: "promote", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "reach",
        fen: board({ P: "e2" }),
        square: "e2",
        prompt: { text: "This pawn hasn't moved yet. Tap every square it can move to.", kid: "Tap where this pawn can go." },
      },
      {
        id: "p2",
        kind: "reach",
        fen: board({ P: "c4", p: ["c5", "b5", "d5"] }),
        square: "c4",
        prompt: { text: "Tap every square this pawn can move to.", kid: "Tap where this pawn can go." },
        hint: { text: "Pawns capture on the slant, not straight ahead." },
      },
      {
        id: "p3",
        kind: "move",
        fen: board({ P: ["b3", "g3"], p: ["b4", "h4"] }),
        goal: "capture",
        answers: ["g3h4"],
        prompt: { text: "Capture a black pawn.", kid: "Grab a black pawn!" },
        hint: { text: "Straight ahead doesn't count." },
      },
      {
        id: "p4",
        kind: "choice",
        prompt: { text: "Can a pawn move backward?" },
        options: [{ text: "Yes" }, { text: "No" }],
        answer: 1,
      },
    ],
    check: [
      {
        id: "c1",
        kind: "reach",
        fen: board({ P: "f2", p: "g3" }),
        square: "f2",
        prompt: { text: "Tap every square this pawn can move to.", kid: "Tap where this pawn can go." },
      },
      {
        id: "c2",
        kind: "move",
        fen: board({ P: ["d4", "a2"], p: ["d5", "e5", "b4"] }),
        goal: "capture",
        answers: ["d4e5"],
        prompt: { text: "Capture a black pawn.", kid: "Grab a black pawn!" },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "How does a pawn capture?" },
        options: [{ text: "Straight forward" }, { text: "Diagonally forward" }, { text: "Any direction" }],
        answer: 1,
      },
    ],
    passMark: 2,
    sources: [SRC],
  },

  {
    id: "s1-setup",
    step: 1,
    title: "Setting Up the Board",
    kidTitle: "Everybody to Their Spots!",
    goal: "Kids can set up all 32 pieces correctly without help.",
    minutes: 15,
    materials: ["One board and a full set per pair"],
    script: [
      {
        say: "Now let's put everybody in their starting spots. First check: light on the right! Pawns fill the second row, like a wall in front.",
        demo: { fen: board({ P: ["a2", "b2", "c2", "d2", "e2", "f2", "g2", "h2"], p: ["a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7"] }) },
      },
      {
        say: "Rooks go in the corners. Knights go next to the rooks. Bishops go next to the knights.",
        demo: {
          fen: board({ R: ["a1", "h1"], N: ["b1", "g1"], B: ["c1", "f1"], r: ["a8", "h8"], n: ["b8", "g8"], b: ["c8", "f8"], P: ["a2", "b2", "c2", "d2", "e2", "f2", "g2", "h2"], p: ["a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7"] }),
        },
      },
      {
        say: "Two squares are left. The queen goes on her own color. The king goes in the last spot. The two queens face each other, and so do the kings.",
        demo: { fen: START_FEN, highlight: ["d1", "d8", "e1", "e8"] },
      },
    ],
    k2Tip: "Say it as a chant while setting up: 'Tower, horse, bishop, queen on her color, king!'",
    commonMistakes: ["King and queen swapped.", "Board turned so a dark square is on the right."],
    activity: {
      title: "Setup Race",
      kidTitle: "Setup Race",
      minutes: 10,
      setup: "All pieces off the board, in a pile beside it.",
      rules: [
        "On 'go', each partner sets up their own side.",
        "When done, raise a hand. Your partner checks your side.",
        "One point for being first, but only if everything is right.",
        "Best of three.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "tap",
        fen: START_FEN,
        prompt: { text: "Tap the white queen.", kid: "Tap the white queen." },
        answers: ["d1"],
      },
      {
        id: "p2",
        kind: "tap",
        fen: START_FEN,
        prompt: { text: "Tap a white knight.", kid: "Tap a white horse." },
        answers: ["b1", "g1"],
      },
      {
        id: "p3",
        kind: "choice",
        prompt: { text: "The white queen starts on a…" },
        options: [{ text: "Light square" }, { text: "Dark square" }],
        answer: 0,
        hint: { text: "The queen goes on her own color." },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "tap",
        fen: START_FEN,
        prompt: { text: "Tap the black king.", kid: "Tap the black king." },
        answers: ["e8"],
      },
      {
        id: "c2",
        kind: "tap",
        fen: START_FEN,
        prompt: { text: "Tap a white bishop.", kid: "Tap a white bishop." },
        answers: ["c1", "f1"],
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "What goes in the corners?" },
        options: [{ text: "Knights" }, { text: "Rooks" }, { text: "Kings" }],
        answer: 1,
      },
    ],
    passMark: 2,
    sources: [SRC],
  },
];
