// Step 4: Special Rules & Draws. Order follows Chess for Children, Part 3
// (castling, promotion, en passant) and Part 4 (how games are drawn), with the
// complete list of draw rules from How to Win at Chess, ch. 6 (50-move rule,
// insufficient material). All wording here is original.

import { after, board } from "../authoring";
import type { Lesson } from "../types";

const CFC3 = "Chess for Children, Part 3 (castling, promotion, en passant)";
const CFC4 = "Chess for Children, Part 4 (draws)";
const HTW = "How to Win at Chess, ch. 6 (every kind of draw)";

export const step4: Lesson[] = [
  {
    id: "s4-castle",
    step: 4,
    title: "Castling",
    kidTitle: "The King's Secret Move",
    goal: "Kids can castle on either side and know the four times castling isn't allowed.",
    minutes: 15,
    materials: ["One board and set per pair"],
    script: [
      {
        say: "Castling is a special move that tucks your king into a safe corner and wakes up a rook, all in one turn. It's the only time you move two pieces at once.",
        demo: { fen: board({ K: "e1", R: ["a1", "h1"], P: ["f2", "g2", "h2"], k: "e8" }, "w", "KQ") },
      },
      {
        say: "To castle, the king steps two squares toward a rook. Then the rook jumps over and lands right next to him, on the other side.",
        do: "On the demo board: king e1 to g1, rook h1 to f1.",
        demo: { fen: board({ K: "e1", R: ["a1", "h1"], P: ["f2", "g2", "h2"], k: "e8" }, "w", "KQ"), arrows: [{ from: "e1", to: "g1" }, { from: "h1", to: "f1" }] },
      },
      {
        say: "You can castle on the short side or the long side. Either way, the king moves two squares. Always move the king first, then the rook.",
        demo: { fen: board({ K: "e1", R: ["a1", "h1"], P: ["f2", "g2", "h2"], k: "e8" }, "w", "KQ"), arrows: [{ from: "e1", to: "c1" }, { from: "a1", to: "d1" }] },
      },
      {
        say: "Four rules. You can't castle if: the king or that rook has already moved; there's a piece in between; your king is in check; or the king would pass over or land on an attacked square.",
        demo: { fen: board({ K: "e1", R: "h1", k: "a8", r: "f8" }, "w", "K"), arrows: [{ from: "f8", to: "f1" }] },
      },
    ],
    k2Tip: "Tell it as a story: the king runs two steps to his castle, and the rook guard jumps over to stand in front of the door.",
    commonMistakes: ["Moving the rook first (many tournaments count that as a rook move).", "Castling out of check.", "Castling after the king has already moved and come back."],
    activity: {
      title: "Castle Race",
      kidTitle: "Castle Race",
      minutes: 10,
      setup: "Normal starting position.",
      rules: [
        "Play a normal game, but the first player to castle scores a point.",
        "To castle, you'll need to move your knight and bishop out of the way first.",
        "Keep playing after someone castles. Can you castle safely before you attack?",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: board({ K: "e1", R: ["a1", "h1"], P: ["f2", "g2", "h2"], k: "e8" }, "w", "KQ"),
        goal: "any",
        answers: ["e1g1"],
        prompt: { text: "Castle on the short side. Move the king two squares toward the h1 rook.", kid: "Castle! Move the king two steps toward the close rook." },
        hint: { text: "Tap the king, then tap g1." },
      },
      {
        id: "p2",
        kind: "move",
        fen: board({ K: "e1", R: ["a1", "h1"], P: ["f2", "g2", "h2"], k: "e8" }, "w", "KQ"),
        goal: "any",
        answers: ["e1c1"],
        prompt: { text: "Now castle on the long side.", kid: "Castle the long way!" },
        hint: { text: "The king still moves only two squares, to c1." },
      },
      {
        id: "p3",
        kind: "choice",
        fen: board({ K: "e1", R: "h1", B: "f1", k: "e8" }, "w", "K"),
        prompt: { text: "Can White castle on the short side right now?" },
        options: [{ text: "Yes" }, { text: "No, a piece is in the way" }, { text: "No, the king is in check" }],
        answer: 1,
      },
      {
        id: "p4",
        kind: "choice",
        fen: board({ K: "e1", R: "h1", k: "a8", r: "f8" }, "w", "K"),
        prompt: { text: "Can White castle on the short side?" },
        options: [{ text: "Yes" }, { text: "No, the king would pass over an attacked square" }],
        answer: 1,
        hint: { text: "Look at the black rook. Which square does it attack?" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: board({ K: "e1", R: ["a1", "h1"], k: "e8", b: "c4" }, "w", "KQ"),
        goal: "any",
        answers: ["e1c1"],
        prompt: { text: "Castle. Only one side is allowed.", kid: "Castle the safe way!" },
      },
      {
        id: "c2",
        kind: "choice",
        fen: board({ K: "e1", R: ["a1", "h1"], k: "a8", r: "e8" }, "w", "KQ"),
        prompt: { text: "Can White castle?" },
        options: [{ text: "Yes, on either side" }, { text: "No, the king is in check" }],
        answer: 1,
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "When you castle, how many squares does the king move?" },
        options: [{ text: "One" }, { text: "Two" }, { text: "Three" }],
        answer: 1,
      },
    ],
    passMark: 2,
    sources: [CFC3],
  },

  {
    id: "s4-promote",
    step: 4,
    title: "Pawn Promotion",
    kidTitle: "Pawn to Queen!",
    goal: "Kids promote a pawn that reaches the last row, usually to a queen.",
    minutes: 15,
    materials: ["One board and set per pair", "Spare queens, or an upside-down rook to stand in for one"],
    script: [
      {
        say: "Remember the pawn's big dream? When a pawn reaches the very last row, it gets promoted. You take it off and put a new piece in its place.",
        demo: { fen: board({ P: "e7" }), arrows: [{ from: "e7", to: "e8" }] },
      },
      {
        say: "You can pick a queen, rook, bishop or knight, of your own color. Almost always you pick the queen, because she's the strongest. That means you can have two queens, or even more!",
        do: "No spare queen? Use an upside-down rook and say it out loud: 'this is a queen'.",
      },
      {
        say: "A pawn can promote by moving forward, or by capturing onto the last row.",
        demo: { fen: board({ P: "d7", r: "e8", n: "d8" }), arrows: [{ from: "d7", to: "e8" }] },
      },
      {
        say: "Pawns that nothing can stop are called passed pawns. Push them! A new queen usually wins the game.",
        demo: { fen: board({ K: "c6", P: "e7", k: "a8", p: "a7" }), arrows: [{ from: "e7", to: "e8" }] },
      },
    ],
    k2Tip: "Make it a celebration: when a pawn promotes, the whole table says 'Hooray, a new queen!'",
    commonMistakes: ["Forgetting to take the pawn off the board.", "Thinking a pawn can promote to a king."],
    activity: {
      title: "Breakthrough",
      kidTitle: "Break Through!",
      minutes: 10,
      setup: "White pawns on a5, b5 and c5. Black pawns on a7, b7 and c7. White moves first.",
      rules: [
        "Only pawns. Take turns.",
        "The first pawn to reach the other side wins.",
        "There's a secret winning trick for White. Can you find it? (Hint: sacrifice a pawn.)",
        "Swap colors and try again.",
      ],
      fen: board({ P: ["a5", "b5", "c5"], p: ["a7", "b7", "c7"] }),
      game: { win: "promote", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: board({ P: "e7", p: "a2" }),
        goal: "any",
        answers: ["e7e8q"],
        prompt: { text: "Promote your pawn.", kid: "Turn your pawn into a queen!" },
      },
      {
        id: "p2",
        kind: "move",
        fen: board({ P: "d7", r: "e8", n: "d8" }),
        goal: "capture",
        answers: ["d7e8q"],
        prompt: { text: "Your pawn is blocked. Promote anyway!", kid: "Grab and turn into a queen!" },
        hint: { text: "Pawns capture diagonally." },
      },
      {
        id: "p3",
        kind: "choice",
        prompt: { text: "Which piece can a pawn NOT promote to?" },
        options: [{ text: "Queen" }, { text: "Knight" }, { text: "King" }],
        answer: 2,
      },
      {
        id: "p4",
        kind: "move",
        fen: board({ K: "c6", P: "e7", k: "a8", p: "a7" }),
        goal: "mate",
        answers: ["e7e8q", "e7e8r"],
        prompt: { text: "Promote and give checkmate in one move.", kid: "Make a queen and checkmate!" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: board({ K: "g6", P: "a7", k: "g8" }),
        goal: "mate",
        answers: ["a7a8q", "a7a8r"],
        prompt: { text: "Promote and give checkmate in one move.", kid: "Make a queen and checkmate!" },
      },
      {
        id: "c2",
        kind: "choice",
        prompt: { text: "Can you have two queens at the same time?" },
        options: [{ text: "Yes, by promoting a pawn" }, { text: "No, only one" }],
        answer: 0,
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Which piece do players choose almost every time they promote?" },
        options: [{ text: "Rook" }, { text: "Queen" }, { text: "Bishop" }],
        answer: 1,
      },
    ],
    passMark: 2,
    sources: [CFC3],
  },

  {
    id: "s4-en-passant",
    step: 4,
    title: "En Passant",
    kidTitle: "The Sneaky Pawn Capture",
    goal: "Kids can capture en passant and know it only works right away. (Best for grade 2 and up.)",
    minutes: 15,
    materials: ["One board and a few pawns per pair"],
    script: [
      {
        say: "Here's the strangest rule in chess. It's called en passant, French for 'in passing'. It's only about pawns.",
        demo: { fen: board({ P: "e5", p: "d7" }, "b") },
      },
      {
        say: "Our pawn is on the fifth row. The black pawn next door jumps two squares, landing right beside ours, as if to sneak past.",
        demo: { fen: board({ P: "e5", p: "d7" }, "b"), arrows: [{ from: "d7", to: "d5" }] },
      },
      {
        say: "We're allowed to capture it as if it had moved only one square. Our pawn moves diagonally to d6, and the black pawn on d5 comes off the board.",
        demo: { fen: after("e4 a6 e5 d5"), arrows: [{ from: "e5", to: "d6" }], highlight: ["d5"] },
      },
      {
        say: "The catch: you must do it on your very next move. Wait one turn and the chance is gone forever.",
      },
    ],
    k2Tip: "Skip this for most K–1 kids; they'll rarely see it. For grade 2, act it out with two kids as pawns walking past each other.",
    commonMistakes: ["Trying it when the pawn moved only one square.", "Trying it a move too late.", "Forgetting to remove the captured pawn (it isn't on the square you land on)."],
    activity: {
      title: "En Passant Hunt",
      minutes: 10,
      setup: "Each partner has 4 pawns. White pawns start on the 5th row, black pawns on their starting squares.",
      rules: [
        "Only pawns. Black moves first.",
        "Whenever a black pawn jumps two squares next to a white pawn, White may capture it en passant.",
        "The first pawn to reach the other side wins.",
        "Swap colors so everyone gets to capture en passant.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: after("e4 a6 e5 d5"),
        goal: "capture",
        answers: ["e5d6"],
        strict: true,
        prompt: { text: "Black just moved d7 to d5. Capture it en passant.", kid: "Catch the sneaky pawn!" },
        hint: { text: "Your pawn moves diagonally to the square the black pawn skipped over." },
      },
      {
        id: "p2",
        kind: "choice",
        fen: after("e4 d6 e5 d5"),
        prompt: { text: "Black's last move was d6 to d5. Can White capture it en passant?" },
        options: [{ text: "Yes" }, { text: "No, it only moved one square" }],
        answer: 1,
      },
      {
        id: "p3",
        kind: "move",
        fen: after("d4 h6 d5 e5"),
        goal: "capture",
        answers: ["d5e6"],
        strict: true,
        prompt: { text: "Black just moved e7 to e5. Capture it en passant.", kid: "Catch the sneaky pawn!" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("e4 Nf6 e5 Nd5 c4 Nb6 c5 d5"),
        goal: "capture",
        answers: ["c5d6", "e5d6"],
        strict: true,
        prompt: { text: "Black just moved d7 to d5. Capture it en passant. There are two ways!", kid: "Catch the sneaky pawn!" },
      },
      {
        id: "c2",
        kind: "choice",
        prompt: { text: "When can you capture en passant?" },
        options: [{ text: "Any time later in the game" }, { text: "Only on the very next move" }],
        answer: 1,
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Which pieces can capture en passant?" },
        options: [{ text: "Only pawns" }, { text: "Any piece" }, { text: "Only knights" }],
        answer: 0,
      },
    ],
    passMark: 2,
    sources: [CFC3],
  },

  {
    id: "s4-draws",
    step: 4,
    title: "Draws and Stalemate",
    kidTitle: "Ties and Stalemate",
    goal: "Kids can tell stalemate from checkmate and know every way a game ends in a draw.",
    minutes: 20,
    materials: ["One board and set per pair"],
    script: [
      {
        say: "Not every game has a winner. A tie in chess is called a draw. The most important one is stalemate: it's your turn, you are NOT in check, but you have no legal move. That's a draw!",
        demo: { fen: board({ K: "b6", Q: "c7", k: "a8" }, "b"), highlight: ["a8"] },
      },
      {
        say: "Compare it with checkmate. Checkmate means in check with no way out, and you lose. Stalemate means not in check but can't move, and it's a draw. Winning players must be careful not to stalemate!",
        demo: { fen: board({ K: "b6", Q: "c8", k: "a8" }, "b"), highlight: ["a8"] },
      },
      {
        say: "Other draws: if nobody has enough pieces left to checkmate, like king against king. If the exact same position happens three times. If both players agree to a draw.",
        demo: { fen: board({ K: "e4", k: "e6" }) },
      },
      {
        say: "And one for long games: if 50 moves go by for each player with no capture and no pawn move, it's a draw. This mostly matters in tournaments.",
      },
    ],
    k2Tip: "Stalemate = 'stuck, but safe'. Checkmate = 'stuck and in trouble'.",
    commonMistakes: ["Calling stalemate a win.", "Grabbing everything with the queen and then stalemating the lone king."],
    activity: {
      title: "Checkmate, Don't Stalemate",
      kidTitle: "Don't Get Stuck!",
      minutes: 15,
      setup: "White: king e1 and queen d1. Black: king e5.",
      rules: [
        "White tries to checkmate the black king.",
        "Black just moves the king and tries to survive.",
        "Stalemate counts as a win for Black! White must be careful.",
        "Swap roles each game.",
      ],
      fen: board({ K: "e1", Q: "d1", k: "e5" }),
      game: { win: "mate", youPlay: "white" },
    },
    practice: [
      {
        id: "p1",
        kind: "choice",
        fen: board({ K: "b6", Q: "c7", k: "a8" }, "b"),
        prompt: { text: "It's Black's turn. What is this?" },
        options: [{ text: "Checkmate" }, { text: "Stalemate" }, { text: "Neither" }],
        answer: 1,
        hint: { text: "Is the black king in check?" },
      },
      {
        id: "p2",
        kind: "choice",
        fen: board({ K: "g6", Q: "g7", k: "g8" }, "b"),
        prompt: { text: "It's Black's turn. What is this?" },
        options: [{ text: "Checkmate" }, { text: "Stalemate" }, { text: "Neither" }],
        answer: 0,
      },
      {
        id: "p3",
        kind: "choice",
        fen: board({ K: "g1", Q: "f6", k: "h8" }, "b"),
        prompt: { text: "It's Black's turn. What is this?" },
        options: [{ text: "Checkmate" }, { text: "Stalemate" }, { text: "Neither" }],
        answer: 2,
        hint: { text: "Can the black king move anywhere?" },
      },
      {
        id: "p4",
        kind: "choice",
        prompt: { text: "Only the two kings are left. What happens?" },
        options: [{ text: "Whoever moves next wins" }, { text: "It's a draw" }, { text: "Keep playing until someone wins" }],
        answer: 1,
      },
    ],
    check: [
      {
        id: "c1",
        kind: "choice",
        fen: board({ K: "f6", P: "f7", k: "f8" }, "b"),
        prompt: { text: "It's Black's turn. What is this?" },
        options: [{ text: "Checkmate" }, { text: "Stalemate" }, { text: "Neither" }],
        answer: 1,
      },
      {
        id: "c2",
        kind: "choice",
        fen: board({ K: "b6", Q: "c3", k: "a8" }),
        prompt: { text: "White to move. Which queen move is a big mistake, because it's stalemate?" },
        options: [{ text: "Qc8" }, { text: "Qc7" }, { text: "Qh8" }],
        answer: 1,
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Which of these is NOT a draw?" },
        options: [{ text: "Stalemate" }, { text: "The same position three times" }, { text: "Checkmate" }, { text: "King against king" }],
        answer: 2,
      },
    ],
    passMark: 2,
    sources: [CFC4, HTW],
  },
];
