// Step 7: Starting Well. Order follows Chess for Children, Part 5 (how to begin
// a game, then planning) and How to Win at Chess, ch. 2–3 and 8 (Center,
// Develop, Castle; traps; a first plan). Move orders are standard opening
// theory (checked against Fundamental Chess Openings). All wording is original.
//
// Opening moves are "best" exercises: Stockfish (npm run validate) proves every
// accepted move is within `margin` of the top move. `strict` keys list only the
// move(s) of our plan, but each one is still engine-approved.

import { after, board, START_FEN } from "../authoring";
import type { Lesson } from "../types";

const CFC = "Chess for Children, Part 5 (beginning a game, planning)";
const HTW2 = "How to Win at Chess, ch. 2–3 (center, develop, castle)";
const HTW8 = "How to Win at Chess, ch. 8 (opening traps, a first repertoire)";
const FCO = "Fundamental Chess Openings (move orders only)";

const ITALIAN = after("e4 e5 Nf3 Nc6 Bc4 Bc5");
const SCHOLAR_THREAT = after("e4 e5 Qh5 Nc6 Bc4");
// Only the d-file is open: the rooks want it.
const OPEN_D = board({ K: "g1", R: ["a1", "f1"], B: "e3", P: ["a2", "b2", "c2", "e4", "f2", "g2", "h2"], k: "g8", r: ["a8", "f8"], b: "e6", p: ["a7", "b7", "c7", "e5", "f7", "g7", "h7"] });

export const step7: Lesson[] = [
  {
    id: "s7-center",
    step: 7,
    title: "Fight for the Center",
    kidTitle: "Grab the Middle",
    goal: "Kids know the four center squares and start the game by putting a pawn there.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair", "Optional: four coins to mark the center squares"],
    script: [
      {
        say: "Look at the four squares in the very middle of the board: d4, e4, d5 and e5. We call them the center. Whoever controls the center usually controls the game.",
        do: "Put a coin on each of the four center squares.",
        demo: { fen: START_FEN, highlight: ["d4", "e4", "d5", "e5"] },
      },
      {
        say: "Why? Pieces in the middle can reach more squares. This knight in the center can jump to eight squares. The knight in the corner can only reach two.",
        demo: { fen: board({ N: ["d4", "h1"] }), highlight: ["b3", "b5", "c2", "c6", "e2", "e6", "f3", "f5", "f2", "g3"] },
      },
      {
        say: "So the best first moves put a pawn in the center: e4 or d4. They also open a door for your bishop and queen to come out.",
        demo: { fen: START_FEN, arrows: [{ from: "e2", to: "e4" }, { from: "d2", to: "d4" }] },
      },
      {
        say: "If your opponent grabs the center, fight back. After e4 and e5, the knight jumps to f3 and attacks the pawn on e5. That's a developing move AND a center move.",
        demo: { fen: after("e4 e5"), arrows: [{ from: "g1", to: "f3" }, { from: "f3", to: "e5" }] },
      },
    ],
    k2Tip: "Call the center 'the playground': everyone wants to play there. Kids touch the four squares before every game.",
    commonMistakes: ["Starting with edge pawns (a- or h-pawn) 'to get the rook out'.", "Moving the f-pawn early, which opens a path to your own king."],
    activity: {
      title: "Center Count",
      kidTitle: "Center Points",
      minutes: 10,
      setup: "Normal game in pairs. Each pair needs paper and a pencil.",
      rules: [
        "Play the first 6 moves each, then stop.",
        "Count how many of the four center squares each player attacks or stands on. One point each.",
        "Most points wins the round. Reset and play again, swapping colors.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "tap",
        fen: START_FEN,
        answers: ["d4", "e4", "d5", "e5"],
        prompt: { text: "Tap one of the four center squares.", kid: "Tap a middle square!" },
        kidMarks: ["d4", "e4", "d5", "e5"],
      },
      {
        id: "p2",
        kind: "move",
        fen: START_FEN,
        goal: "best",
        strict: true,
        answers: ["e2e4", "d2d4"],
        prompt: { text: "First move of the game: put a pawn in the center.", kid: "Move a pawn to the middle!" },
        hint: { text: "Move the e-pawn or the d-pawn two squares." },
      },
      {
        id: "p3",
        kind: "choice",
        prompt: { text: "Why do pieces like the center?", kid: "Why is the middle good?" },
        options: [
          { text: "They can reach more squares from there", kid: "They can go more places" },
          { text: "It's the only place they're safe", kid: "Nobody can take them there" },
          { text: "It's a rule of chess", kid: "It's a rule" },
        ],
        answer: 0,
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("e4 e5"),
        goal: "best",
        strict: true,
        answers: ["g1f3"],
        prompt: { text: "Bring out a piece that attacks Black's center pawn.", kid: "Bring out a horse that attacks the pawn in the middle!" },
        hint: { text: "Which knight can attack e5?" },
      },
      {
        id: "c2",
        kind: "move",
        fen: after("d4 d5"),
        goal: "best",
        strict: true,
        answers: ["c2c4"],
        prompt: { text: "Play a pawn move that attacks Black's center pawn on d5.", kid: "Use a pawn to attack the pawn on d5!" },
        hint: { text: "Pawns attack one square diagonally forward. Which pawn could reach a square next to d5?" },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Which of these is a center square?" },
        options: [{ text: "a1" }, { text: "e4" }, { text: "h8" }],
        answer: 1,
      },
    ],
    passMark: 2,
    sources: [CFC, HTW2, FCO],
  },

  {
    id: "s7-develop",
    step: 7,
    title: "Develop Your Pieces",
    kidTitle: "Wake Up Your Pieces",
    goal: "Kids bring knights and bishops out early, move each piece once, and keep the queen home.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair"],
    script: [
      {
        say: "'Developing' means bringing a piece off the back row so it can help. In the opening, the knights and bishops come out first.",
        demo: { fen: ITALIAN, arrows: [{ from: "g1", to: "f3" }, { from: "f1", to: "c4" }] },
      },
      {
        say: "Three opening rules. One: develop a new piece every move. Don't move the same piece twice unless you have to. Two: knights usually come out before bishops. Three: keep your queen home for now.",
      },
      {
        say: "Why not the queen? If she comes out early, the other side develops pieces AND attacks her at the same time. Here Black's knight comes out and chases the queen. Black gains time, White loses it.",
        demo: { fen: after("e4 e5 Qh5 Nf6"), arrows: [{ from: "f6", to: "h5" }] },
      },
      {
        say: "A quick test: count how many knights and bishops each side has moved. The player with more pieces out is usually winning the opening.",
      },
    ],
    k2Tip: "Pieces are 'asleep' on the back row. Every developing move 'wakes one up'. Count the sleepy pieces together.",
    commonMistakes: ["Moving the same knight three times while other pieces sleep.", "Bringing the queen out on move 2 or 3.", "Blocking the d- or e-pawn with a bishop (Bd3 before d-pawn moves)."],
    activity: {
      title: "Wake-Up Race",
      kidTitle: "Wake-Up Race",
      minutes: 10,
      setup: "Normal game in pairs.",
      rules: [
        "Race to develop all four knights and bishops and castle.",
        "The first player to get all four minor pieces out AND castle scores a point.",
        "Moving the queen before move 6 costs a point. Keep playing the game after the race.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6"),
        goal: "best",
        strict: true,
        answers: ["f1c4", "f1b5"],
        prompt: { text: "Develop your bishop to a good square.", kid: "Bring out a bishop!" },
        hint: { text: "The light-squared bishop can now come out. Aim it toward Black's side." },
      },
      {
        id: "p2",
        kind: "choice",
        fen: after("e4 e5 Nf3 Nc6"),
        prompt: { text: "White to move. Which move develops a piece?", kid: "Which move wakes up a piece?" },
        options: [{ text: "h3" }, { text: "Nc3" }, { text: "Ke2" }],
        answer: 1,
      },
      {
        id: "p3",
        kind: "tap",
        fen: ITALIAN,
        answers: ["b1", "c1"],
        prompt: { text: "Tap a white knight or bishop that hasn't been developed yet.", kid: "Tap a white horse or bishop that's still asleep." },
        hint: { text: "Look at White's back row." },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("d4 d5 c4 e6"),
        goal: "best",
        strict: true,
        answers: ["b1c3", "g1f3"],
        prompt: { text: "Develop a knight.", kid: "Bring out a horse!" },
      },
      {
        id: "c2",
        kind: "move",
        fen: after("e4 e5 Nf3"),
        goal: "best",
        strict: true,
        answers: ["b8c6"],
        orientation: "black",
        prompt: { text: "Black: develop a piece AND protect the pawn on e5.", kid: "Black: bring out a horse to guard e5!" },
        hint: { text: "Which black knight can reach a square that guards e5?" },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "In the opening, how often should you move each piece?" },
        options: [{ text: "Once, until all your pieces are out" }, { text: "As often as you like" }, { text: "Only move the queen" }],
        answer: 0,
      },
    ],
    passMark: 2,
    sources: [CFC, HTW2],
  },

  {
    id: "s7-castle",
    step: 7,
    title: "Castle Early",
    kidTitle: "Hide Your King",
    goal: "Kids castle in the first ten moves and keep the pawns in front of their king.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair"],
    script: [
      {
        say: "A king in the middle is in danger. Once pawns start trading, lines open up and the enemy pieces rush in. So: develop, then castle. Try to castle in your first ten moves.",
        demo: { fen: ITALIAN, arrows: [{ from: "e1", to: "g1" }] },
      },
      {
        say: "To castle short, the knight and bishop between your king and rook must be out of the way. That's another reason to develop them early.",
        demo: { fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 O-O"), highlight: ["g1", "f1"] },
      },
      {
        say: "After castling, the three pawns in front of your king are its shield. Leave them alone! Every pawn you push there makes a hole an enemy piece can use.",
        demo: { fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 O-O"), highlight: ["f2", "g2", "h2"] },
      },
      {
        say: "Castling also brings your rook toward the middle, where it can join the game. Two jobs in one move.",
      },
    ],
    k2Tip: "The king goes 'home to his castle' and the pawns are 'the wall'. Never knock down your own wall.",
    commonMistakes: ["Forgetting to castle until the king gets attacked.", "Pushing the g- or h-pawn right after castling.", "Castling into an attack (check CCA first)."],
    activity: {
      title: "Castle by Ten",
      kidTitle: "Castle by Ten",
      minutes: 10,
      setup: "Normal game in pairs.",
      rules: [
        "Each player must castle by their 10th move.",
        "Castled in time: one point. Didn't castle: your partner gets a point.",
        "Pushing a pawn in front of your castled king before move 15 costs a point.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: ITALIAN,
        goal: "best",
        strict: true,
        answers: ["e1g1"],
        prompt: { text: "Your pieces are out. Make your king safe.", kid: "Hide your king in the castle!" },
        hint: { text: "Castle: the king moves two squares toward the rook." },
      },
      {
        id: "p2",
        kind: "choice",
        prompt: { text: "Before you can castle on the short side, which pieces must move out of the way?" },
        options: [{ text: "The knight and the bishop" }, { text: "The queen and the rook" }, { text: "All the pawns" }],
        answer: 0,
      },
      {
        id: "p3",
        kind: "choice",
        prompt: { text: "After castling, should you push the pawns in front of your king?", kid: "After you castle, should you move the pawns next to your king?" },
        options: [
          { text: "Usually not: they're the king's shield", kid: "No, they protect the king" },
          { text: "Yes, push them all", kid: "Yes, push them" },
        ],
        answer: 0,
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 O-O Nf6 d3"),
        goal: "best",
        strict: true,
        answers: ["e8g8"],
        orientation: "black",
        prompt: { text: "Black: make your king safe.", kid: "Black: hide your king!" },
      },
      {
        id: "c2",
        kind: "move",
        fen: after("d4 d5 Nf3 Nf6 e3 e6 Bd3 Be7"),
        goal: "best",
        strict: true,
        answers: ["e1g1"],
        prompt: { text: "Make your king safe.", kid: "Hide your king!" },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Why castle early?" },
        options: [{ text: "The king is safer, and a rook comes into the game" }, { text: "It wins a pawn" }, { text: "You must castle before move 5" }],
        answer: 0,
      },
    ],
    passMark: 2,
    sources: [CFC, HTW2],
  },

  {
    id: "s7-traps",
    step: 7,
    title: "Opening Traps",
    kidTitle: "Don't Fall for It!",
    goal: "Kids can play and stop Scholar's Mate and Fool's Mate, and punish an early queen.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair"],
    script: [
      {
        say: "Here's a famous trap called Scholar's Mate. White brings the queen and bishop out early. Both aim at f7, the weakest square near Black's king, because only the king guards it.",
        demo: { fen: SCHOLAR_THREAT, arrows: [{ from: "h5", to: "f7" }, { from: "c4", to: "f7" }] },
      },
      {
        say: "If Black doesn't notice, queen takes f7 is checkmate. Many beginners lose this way.",
        demo: { fen: after("e4 e5 Qh5 Nc6 Bc4 Nf6 Qxf7#"), highlight: ["f7", "e8"] },
      },
      {
        say: "Stopping it is easy once you see it. Block the queen with g6, or guard f7 with your queen on e7 or f6. Then attack the white queen with your pieces, and you're ahead in development.",
        demo: { fen: after("e4 e5 Qh5 Nc6 Bc4 g6"), arrows: [{ from: "g6", to: "h5" }] },
      },
      {
        say: "The fastest checkmate ever is Fool's Mate: White weakens the king with f3 and g4, and Black's queen mates on h4. The lesson: don't move the pawns in front of your king in the opening.",
        demo: { fen: after("f3 e5 g4 Qh4#"), arrows: [{ from: "d8", to: "h4" }] },
      },
    ],
    k2Tip: "Teach f7 as 'the weak spot'. Kids put a finger on f7 (or f2) and ask 'is anyone attacking it?'",
    commonMistakes: ["Trying Scholar's Mate every game. A good opponent stops it and you're behind.", "Defending f7 with ...Nh6 or ...f6 when ...g6 or ...Qe7 is simpler."],
    activity: {
      title: "Trap Defense",
      kidTitle: "Stop the Trap",
      minutes: 10,
      setup: "In pairs. One player is White and must try Scholar's Mate (e4, Qh5, Bc4, Qxf7).",
      rules: [
        "Black's job: stop it, then chase the queen with pieces.",
        "If Black survives to move 10 with no lost pieces, Black scores a point.",
        "Swap colors and repeat. Then play a normal game.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: after("e4 e5 Bc4 Nc6 Qh5 Nf6"),
        goal: "mate",
        answers: ["h5f7"],
        prompt: { text: "Black didn't see the trap. Checkmate in one!", kid: "Find checkmate!" },
        hint: { text: "Which square do the queen and bishop both attack?" },
      },
      {
        id: "p2",
        kind: "move",
        fen: SCHOLAR_THREAT,
        goal: "best",
        margin: 100,
        answers: ["d8e7", "g7g6", "d8f6", "g8h6"],
        orientation: "black",
        prompt: { text: "Black: White threatens Qxf7 checkmate. Stop it!", kid: "Black: stop the checkmate on f7!" },
        hint: { text: "Block the queen's path, or guard f7 one more time." },
      },
      {
        id: "p3",
        kind: "move",
        fen: after("f3 e5 g4"),
        goal: "mate",
        answers: ["d8h4"],
        orientation: "black",
        prompt: { text: "Black: White pushed the pawns in front of the king. Checkmate in one!", kid: "Black: find checkmate!" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("e4 e5 Qh5 Nc6 Bc4 Nf6"),
        goal: "mate",
        answers: ["h5f7"],
        prompt: { text: "Checkmate in one.", kid: "Find checkmate!" },
      },
      {
        id: "c2",
        kind: "move",
        fen: after("e4 e5 Qh5 Nc6 Bc4 g6 Qf3"),
        goal: "best",
        answers: ["g8f6", "g8h6", "d8e7", "d8f6", "f7f5"],
        orientation: "black",
        prompt: { text: "Black: the queen moved, but it still aims at f7 with the bishop. Stop the checkmate again!", kid: "Black: stop the checkmate on f7 again!" },
        hint: { text: "A knight move can block the queen's line and develop at the same time." },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Which square does Scholar's Mate attack?" },
        options: [{ text: "e5" }, { text: "f7" }, { text: "h7" }],
        answer: 1,
      },
    ],
    passMark: 2,
    sources: [CFC, HTW8],
    extra: "opening",
  },

  {
    id: "s7-italian",
    step: 7,
    title: "A Plan for White: the Italian Game",
    kidTitle: "White's Plan",
    goal: "Kids can play the Italian Game: e4, Nf3, Bc4, castle, then c3 and d3 or d4.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair", "Optional: the plan written on a card"],
    script: [
      {
        say: "Now we put the rules together into a plan for White. It's called the Italian Game, and strong players still use it. Move 1: e4 takes the center.",
        demo: { fen: START_FEN, arrows: [{ from: "e2", to: "e4" }] },
      },
      {
        say: "Move 2: knight to f3. It develops and attacks e5. Black usually defends with the knight on c6. Move 3: bishop to c4. It aims at f7, the weak square.",
        demo: { fen: after("e4 e5 Nf3 Nc6 Bc4"), arrows: [{ from: "c4", to: "f7" }] },
      },
      {
        say: "Next: castle to keep the king safe. Then play c3 and d4 to build a big center, or d3 for a calm game. Then the rook comes to e1.",
        demo: { fen: ITALIAN, arrows: [{ from: "e1", to: "g1" }, { from: "c2", to: "c3" }, { from: "d2", to: "d4" }] },
      },
      {
        say: "Write the plan on a card: e4, Nf3, Bc4, castle, c3, d3 or d4, Re1. If Black does something strange, go back to the rules: center, develop, castle.",
        do: "Write the plan on the board for kids to copy.",
      },
    ],
    k2Tip: "Use a rhyme: 'Pawn, horse, bishop, castle'. Kids say it as they make the first four moves.",
    commonMistakes: ["Playing Ng5 early to attack f7 when the attack doesn't work.", "Forgetting to castle because the plan 'didn't say when'."],
    activity: {
      title: "Plan Practice",
      kidTitle: "Plan Practice",
      minutes: 10,
      setup: "In pairs, both players have the plan card.",
      rules: [
        "White plays the Italian Game plan. Black plays e5, Nc6, Bc5 or Nf6, and castles.",
        "Stop after 8 moves each. Did White follow the plan? Did both kings castle?",
        "Swap colors and play again, then finish a game.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: after("e4 e5"),
        goal: "best",
        strict: true,
        answers: ["g1f3"],
        prompt: { text: "Italian Game, move 2: develop and attack e5.", kid: "Plan move 2: the horse!" },
      },
      {
        id: "p2",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6"),
        goal: "best",
        strict: true,
        answers: ["f1c4"],
        prompt: { text: "Italian Game, move 3: aim a bishop at f7.", kid: "Plan move 3: the bishop!" },
        hint: { text: "From c4, the bishop looks straight at f7." },
      },
      {
        id: "p3",
        kind: "move",
        fen: ITALIAN,
        goal: "best",
        strict: true,
        answers: ["e1g1", "c2c3", "d2d3"],
        prompt: { text: "Black copied you. Play the next move of the plan.", kid: "What's next in the plan?" },
        hint: { text: "Castle, or play c3 or d3." },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6 Bc4 Nf6"),
        goal: "best",
        strict: true,
        answers: ["d2d3", "b1c3"],
        prompt: { text: "Black's knight attacks your e4 pawn. Protect it and keep developing.", kid: "Guard your e4 pawn!" },
        hint: { text: "A pawn or a knight can guard e4." },
      },
      {
        id: "c2",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6"),
        goal: "best",
        strict: true,
        answers: ["d2d4", "d2d3"],
        prompt: { text: "You played c3. What's the next pawn move in the plan?", kid: "Next pawn move in the plan?" },
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "In the Italian Game, which square does White's bishop on c4 aim at?" },
        options: [{ text: "f7" }, { text: "h7" }, { text: "a6" }],
        answer: 0,
      },
    ],
    passMark: 2,
    sources: [HTW8, FCO],
    openingLab: "Italian Game",
  },

  {
    id: "s7-black",
    step: 7,
    title: "A Plan for Black: Answer in the Center",
    kidTitle: "Black's Plan",
    goal: "Kids answer 1.e4 with ...e5 and 1.d4 with ...d5, then develop and castle.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair"],
    script: [
      {
        say: "Black's plan is simple: copy the idea. If White puts a pawn on e4, Black answers e5. If White plays d4, Black plays d5. Black gets a share of the center right away.",
        demo: { fen: after("e4 e5"), orientation: "black", arrows: [{ from: "e7", to: "e5" }] },
      },
      {
        say: "After 1.e4 e5: knight to c6 to guard e5, then bishop to c5 or knight to f6, then castle. It's the Italian plan, with Black's pieces.",
        demo: { fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5"), orientation: "black", arrows: [{ from: "b8", to: "c6" }, { from: "f8", to: "c5" }] },
      },
      {
        say: "After 1.d4 d5, White often plays c4 to attack d5. Black keeps the pawn there with e6. Then: knight to f6, bishop to e7, castle.",
        demo: { fen: after("d4 d5 c4 e6"), orientation: "black", arrows: [{ from: "e7", to: "e6" }, { from: "e6", to: "d5" }] },
      },
      {
        say: "If White plays something you don't know, use the rules. Take a center square, develop a new piece each move, castle.",
      },
    ],
    k2Tip: "Black's plan is 'mirror, then wake up the pieces'. Kids mirror White's first move, then develop.",
    commonMistakes: ["Answering 1.e4 with an edge pawn.", "Grabbing pawns with the queen instead of developing.", "Playing ...f6 to guard e5 (it weakens the king)."],
    activity: {
      title: "Mirror Openings",
      kidTitle: "Mirror Game",
      minutes: 10,
      setup: "In pairs. The coach calls out 'e4!' or 'd4!' for White's first move.",
      rules: [
        "White plays the called move. Black answers in the center (e5 or d5).",
        "Both sides develop and castle. Stop after 8 moves each and check: did Black follow the plan?",
        "Swap colors and play again, then finish a game.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "move",
        fen: after("e4"),
        goal: "best",
        strict: true,
        answers: ["e7e5"],
        orientation: "black",
        prompt: { text: "Black: White played e4. Answer in the center.", kid: "Black: put your pawn in the middle too!" },
      },
      {
        id: "p2",
        kind: "move",
        fen: after("d4"),
        goal: "best",
        strict: true,
        answers: ["d7d5"],
        orientation: "black",
        prompt: { text: "Black: White played d4. Answer in the center.", kid: "Black: put your pawn in the middle too!" },
      },
      {
        id: "p3",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6 Bc4"),
        goal: "best",
        strict: true,
        answers: ["f8c5", "g8f6"],
        orientation: "black",
        prompt: { text: "Black: develop your next piece.", kid: "Black: bring out a bishop or a horse!" },
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: after("d4 d5 c4"),
        goal: "best",
        strict: true,
        answers: ["e7e6", "c7c6"],
        orientation: "black",
        prompt: { text: "Black: White attacks d5. Protect it with a pawn.", kid: "Black: guard your d5 pawn with a pawn!" },
      },
      {
        id: "c2",
        kind: "move",
        fen: after("d4 d5 c4 e6 Nc3"),
        goal: "best",
        strict: true,
        answers: ["g8f6", "f8e7"],
        orientation: "black",
        prompt: { text: "Black: develop a piece so you can castle soon.", kid: "Black: wake up a piece near your king!" },
      },
      {
        id: "c3",
        kind: "move",
        fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 O-O"),
        goal: "best",
        strict: true,
        answers: ["g8f6", "d7d6"],
        orientation: "black",
        prompt: { text: "Black: White castled. Keep developing.", kid: "Black: wake up another piece!" },
        hint: { text: "The knight on g8 is still asleep. Or open a door for the other bishop." },
      },
    ],
    passMark: 2,
    sources: [HTW8, FCO],
    openingLab: "Black replies (1...e5 and 1...d5)",
  },

  {
    id: "s7-plan",
    step: 7,
    title: "After the Opening: Make a Plan",
    kidTitle: "What Now?",
    goal: "Kids have a simple routine once the opening is done: CCA, improve the worst piece, rooks to open files.",
    minutes: 15,
    materials: ["Demo board", "One board and set per pair"],
    script: [
      {
        say: "Your pieces are out and your king is castled. Now what? Here's a three-step routine for every move after the opening.",
      },
      {
        say: "Step one is always CCA: checks, captures, attacks, for both sides. Tactics come first.",
      },
      {
        say: "Step two: find your worst piece and make it better. Here White's bishop on c1 is stuck behind its own pawns. A good plan is to move the d-pawn so it can come out.",
        demo: { fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 O-O Nf6 Nc3 O-O"), highlight: ["c1"], arrows: [{ from: "d2", to: "d3" }] },
      },
      {
        say: "Step three: put your rooks on open files. An open file is a column with no pawns on it. Rooks love open files because they can see all the way down the board.",
        demo: { fen: OPEN_D, highlight: ["d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8"], arrows: [{ from: "f1", to: "d1" }] },
      },
      {
        say: "And don't push pawns without a reason, especially near your king. Pawns can't move backward, so every push leaves a square behind that no pawn can guard again.",
      },
    ],
    k2Tip: "Ask 'Which piece is sad?' The sad piece has nothing to do. Make it happy by giving it a better square.",
    commonMistakes: ["Moving pieces back and forth with no plan.", "Leaving a rook in the corner all game.", "Pushing pawns 'because nothing else to do'."],
    activity: {
      title: "Sad Piece",
      kidTitle: "Find the Sad Piece",
      minutes: 10,
      setup: "Normal game in pairs.",
      rules: [
        "Every few moves, either player can call 'Sad piece!'.",
        "Both players point to their own worst piece and say how to make it better.",
        "Bonus point for getting a rook onto an open file.",
      ],
    },
    practice: [
      {
        id: "p1",
        kind: "tap",
        fen: after("e4 e5 Nf3 Nc6 Bc4 Bc5 O-O Nf6 Nc3 O-O"),
        answers: ["c1"],
        prompt: { text: "Tap White's worst piece: the one stuck behind its own pawns.", kid: "Tap the white piece that is stuck." },
        hint: { text: "Which white piece has no moves at all?" },
      },
      {
        id: "p2",
        kind: "move",
        fen: OPEN_D,
        goal: "best",
        strict: true,
        answers: ["f1d1", "a1d1"],
        prompt: { text: "Only one file is open. Put a rook on it.", kid: "Put a rook on the empty column!" },
        hint: { text: "Look for the column with no pawns." },
      },
      {
        id: "p3",
        kind: "choice",
        prompt: { text: "What is an open file?" },
        options: [{ text: "A column with no pawns on it" }, { text: "A row with no pieces" }, { text: "A square nobody attacks" }],
        answer: 0,
      },
    ],
    check: [
      {
        id: "c1",
        kind: "move",
        fen: board({ K: "g1", R: ["a1", "f1"], B: "e3", P: ["a2", "b2", "c2", "e4", "f2", "g2", "h2"], k: "g8", r: ["a8", "f8"], b: "e6", p: ["a7", "b7", "c7", "e5", "f7", "g7", "h7"] }, "b"),
        goal: "best",
        strict: true,
        answers: ["f8d8", "a8d8"],
        orientation: "black",
        prompt: { text: "Black: put a rook on the open file.", kid: "Black: rook to the empty column!" },
      },
      {
        id: "c2",
        kind: "choice",
        prompt: { text: "Your pieces are out and your king is safe. What's the FIRST thing to check every move?" },
        options: [{ text: "Checks, captures and attacks" }, { text: "Which pawn to push" }, { text: "How to bring out the queen" }],
        answer: 0,
      },
      {
        id: "c3",
        kind: "choice",
        prompt: { text: "Why should you be careful pushing pawns?" },
        options: [{ text: "Pawns can't move backward" }, { text: "Pawns can only move once" }, { text: "Pushing a pawn is against the rules" }],
        answer: 0,
      },
    ],
    passMark: 2,
    sources: [CFC, HTW2],
  },
];
